# Generated by Django 6.0.5 on 2026-05-19 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('forwarded', 'Forwarded to Authority'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('forwarded', 'Forwarded to Authority'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='old_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('forwarded', 'Forwarded to Authority'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], max_length=20),
        ),
        migrations.CreateModel(
            name='ComplaintForwardLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_logs', to='complaints.complaint')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_forward_logs', to='departments.department')),
                ('forwarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_forward_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Forward Log',
                'verbose_name_plural': 'Complaint Forward Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
