# Generated by Django 6.0.5 on 2026-05-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_status_alter_statusupdate_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_genuineness_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_genuineness_score',
            field=models.FloatField(blank=True, help_text='AI confidence that this is a genuine civic complaint', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_validation_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
